### ISSUE TITLE
Serial Issue

### ISSUE THREAD

**Issue by guy16510** [Pecacheu/create2#3]
https://github.com/Pecacheu/create2/blob/5dc05fdd097caba0bb90de9f697f57c39546ef8f/index.js#L88

Hey If you change the following it will fix this broken code:

`  serial = new Serial (port, {
    //Defaults for Roomba Open Interface:
    baudRate: 115200,
    dataBits: 8,
    parity: 'none',
    stopBits: 1,
    flowControl: false,
  });`

**Comment by guy16510** [comment]
That sounded rude.. I love your library, and I am playing with it. Hopefully this helps for any future users.

**Comment by Pecacheu** [comment]
Ah, accepted. Sorry, I am not active enough on GitHub at all xD
